admin_section/urls.py
from django.urls import path
from admin_section import views

app_name = 'admin_section'

urlpatterns = [
    path('', views.log_in, name='login'),
    path('news_admin/', views.news_admin, name='news_admin'),
    path('admin_bangladesh/', views.admin_bangladesh, name='admin_bangladesh'),
    path('admin_international/', views.admin_international, name='admin_international'),
    path('admin_entertainment/', views.admin_entertainment, name='admin_entertainment'),
    path('admin_sports/', views.admin_sports, name='admin_sports'),
    path('admin_trade/', views.admin_trade, name='admin_trade'),
    
]

newspaper_project/urls.py
from django.urls import path
from newspaper_project import views

app_name = 'newspaper_project'

urlpatterns = [
    path('', views.home, name='home'),
    path('news_details/<pk>/<table>', views.news_details, name='news_details'),
    path('news_Bangladesh/', views.news_Bangladesh, name='news_Bangladesh'),
    path('news_International/', views.news_International, name='news_International'),
    path('news_Trade/', views.news_Trade, name='news_Trade'),
    path('news_Entertainment/', views.news_Entertainment, name='news_Entertainment'),
    path('news_Sports/', views.news_Sports, name='news_Sports'),
    
]

online_newspaper/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newspaper_project.urls')),
    path('my_admin', include('admin_section.urls')),
    # path('account/', include('app_login.urls')),
    # path('user/', include('app_user_activity.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

newspaper_project/models.py
from django.db import models
from django.db.models.base import Model

# Create your models here.
class Bangladesh(models.Model):
    Title = models.CharField(max_length=300)
    Content = models.TextField()
    content_image = models.ImageField(upload_to='Bangladesh_pic',verbose_name='Uplod Image')
    publish_time = models.DateTimeField(auto_now_add=True,null=True,blank=True)

    class Meta:
        ordering = ('-publish_time', )

    def __str__(self):
        return self.Title

class International(models.Model):
    Title = models.CharField(max_length=300)
    Content = models.TextField()
    content_image = models.ImageField(upload_to='International_pic',verbose_name='Uplod Image')
    publish_time = models.DateTimeField(auto_now_add=True,null=True,blank=True)

    class Meta:
        ordering = ('-publish_time', )

    def __str__(self):
        return self.Title

class Trade(models.Model):
    Title = models.CharField(max_length=300)
    Content = models.TextField()
    content_image = models.ImageField(upload_to='Trade_pic',verbose_name='Uplod Image')
    publish_time = models.DateTimeField(auto_now_add=True,null=True,blank=True)

    class Meta:
        ordering = ('-publish_time', )

    def __str__(self):
        return self.Title

class Entertainment(models.Model):
    Title = models.CharField(max_length=300)
    Content = models.TextField()
    content_image = models.ImageField(upload_to='Entertainment_pic',verbose_name='Uplod Image')
    publish_time = models.DateTimeField(auto_now_add=True,null=True,blank=True)

    class Meta:
        ordering = ('-publish_time', )

    def __str__(self):
        return self.Title

class Sports(models.Model):
    Title = models.CharField(max_length=300)
    Content = models.TextField()
    content_image = models.ImageField(upload_to='Sports_pic',verbose_name='Uplod Image')
    publish_time = models.DateTimeField(auto_now_add=True,null=True,blank=True)

    class Meta:
        ordering = ('-publish_time', )

    def __str__(self):
        return self.Title

newspaper_project/views.py
from django.shortcuts import render,HttpResponseRedirect
# from newspaper_project import forms
from newspaper_project import models
from django.apps import apps
from django.core.paginator import Paginator

# Create your views here.
def home(request):
    top_news_bd = models.Bangladesh.objects.all()[:1]
    top_news_int = models.International.objects.all()[:1]
    top_news_ent = models.Entertainment.objects.all()[:1]
    top_news_trd = models.Trade.objects.all()[:1]
    top_news_sports = models.Sports.objects.all()[:1]
    top_news = {'top_news_sports':top_news_sports, 'top_news_trd':top_news_trd, 'top_news_ent':top_news_ent, 'top_news_int':top_news_int, 'top_news_bd':top_news_bd}

    bangladesh_news = models.Bangladesh.objects.all()[:6]
    international_news = models.International.objects.all()[:6]
    trade_news = models.Trade.objects.all()[:6]
    entertainment_news = models.Entertainment.objects.all()[:6]
    sports_news = models.Sports.objects.all()[:6]

    diction = {'top_news':top_news,'bangladesh_news':bangladesh_news, 'trade_news':trade_news, 'international_news':international_news, 'entertainment_news':entertainment_news, 'sports_news':sports_news}
    return render(request,'newspaper_project/home.html',context=diction)


def news_details(request,pk,table):
    news = getattr(models, table).objects.get(pk=pk)
    related_news = getattr(models, table).objects.exclude(pk=pk)[:5]
    # paginator = Paginator(related_news, )
	# page_number = request.GET.get('page')
	# page_obj = paginator.get_page(page_number)
    diction = {'news':news,'related_news':related_news}
    return render(request,'newspaper_project/news_details.html',context=diction)


def news_Bangladesh(request):
    news = models.Bangladesh.objects.all()
    paginator = Paginator(news,5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    diction = {'page_obj':page_obj, 'headline':'বাংলাদেশ'}
    return render(request,'newspaper_project/news_all.html',context=diction)


def news_International(request):
    news = models.International.objects.all()
    paginator = Paginator(news,5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    diction = {'page_obj':page_obj, 'headline':'আন্তর্জাতিক'}
    return render(request,'newspaper_project/news_all.html',context=diction)

def news_Trade(request):
    news = models.Trade.objects.all()
    paginator = Paginator(news,5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    diction = {'page_obj':page_obj, 'headline':'বাণিজ্য'}
    return render(request,'newspaper_project/news_all.html',context=diction)

def news_Entertainment(request):
    news = models.Entertainment.objects.all()
    paginator = Paginator(news,5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    diction = {'page_obj':page_obj, 'headline':'বিনোদন'}
    return render(request,'newspaper_project/news_all.html',context=diction)

def news_Sports(request):
    news = models.Sports.objects.all()
    paginator = Paginator(news,5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    diction = {'page_obj':page_obj, 'headline':'খেলাধুলা'}
    return render(request,'newspaper_project/news_all.html',context=diction)

templates/newspaper_project/home.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block block_title %}
    Home
{% endblock block_title %}


{% block body_block %}
    <div class="row">
        <h3><b>শীর্ষ সংবাদ</b></h3>
        <hr>
        {% for key,news in top_news.items %}
        {% for news_top in news %}
            <div class="col-sm-4" style=" border-right: 1px solid #6C758E;">
                <div class="card">
                    <img src="/media/{{ news_top.content_image }}" class="card-img-top img-fluid " alt="{{ news_top.Title }}" style="display: block; width: 100%; height: 200px;">
                    <div class="card-body">
                        <a href="{% url 'newspaper_project:news_details' pk=news_top.pk table=news_top|model_name %}" style="text-decoration:none;color:black;"><h5 class="card-title">{{ news_top.Title }}</h5></a>
                        <p class="card-text"><small class="text-muted">{{ news_top.publish_time }}</small></p>
                        <p class="card-text">{{ news_top.Content|range_filter }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% endfor %}
    </div> 

   
    <div class="row mt-4">
         <hr>
        <h4><b>বাংলাদেশ</b></h4>
        <hr>
        {% for news in bangladesh_news %}
            <div class="col-sm-4" style=" border-right: 1px solid #6C758E;">
                <div class="card">
                    <img src="/media/{{ news.content_image }}" class="card-img-top img-fluid" alt="{{ news.Title }}" style="display: block; width: 100%; height: 200px;">
                    <div class="card-body">
                        <a href="{% url 'newspaper_project:news_details' pk=news.pk table='Bangladesh' %}" style="text-decoration:none;color:black;"><h5 class="card-title">{{ news.Title }}</h5></a>
                        <p class="card-text"><small class="text-muted">{{ news.publish_time }}</small></p>
                        <p class="card-text">{{ news.Content|range_filter }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    
    <div class="row mt-4">
        <hr>
        <h4><b>আন্তর্জাতিক</b></h4>
        <hr>
        {% for news in international_news %}
            <div class="col-sm-4" style=" border-right: 1px solid #6C758E;">
                <div class="card">
                    <img src="/media/{{ news.content_image }}" class="card-img-top img-thumbnail" alt="{{ news.Title }}" style="display: block; width: 100%; height: 200px;">
                    <div class="card-body">
                        <a href="{% url 'newspaper_project:news_details' pk=news.pk table='International' %}" style="text-decoration:none;color:black;"><h5 class="card-title">{{ news.Title }}</h5></a>
                        <p class="card-text"><small class="text-muted">{{ news.publish_time }}</small></p>
                        <p class="card-text">{{ news.Content|range_filter }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <hr>
    <h4><b>বাণিজ্য</b></h4>
    <div class="row">
        <hr>
        {% for news in trade_news %}
            <div class="col-sm-4" style=" border-right: 1px solid #6C758E;">
                <div class="card">
                    <img src="/media/{{ news.content_image }}" class="card-img-top img-thumbnail" alt="{{ news.Title }}" style="display: block; width: 100%; height: 200px;">
                    <div class="card-body">
                        <a href="{% url 'newspaper_project:news_details' pk=news.pk table='Trade' %}" style="text-decoration:none;color:black;"><h5 class="card-title">{{ news.Title }}</h5></a>
                        <p class="card-text"><small class="text-muted">{{ news.publish_time }}</small></p>
                        <p class="card-text">{{ news.Content|range_filter }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <hr>
    <h4><b>বিনোদন</b></h4>
    <div class="row">
        <hr>
        {% for news in entertainment_news %}
            <div class="col-sm-4" style=" border-right: 1px solid #6C758E;">
                <div class="card">
                    <img src="/media/{{ news.content_image }}" class="card-img-top img-thumbnail" alt="{{ news.Title }}" style="display: block; width: 100%; height: 200px;">
                    <div class="card-body">
                        <a href="{% url 'newspaper_project:news_details' pk=news.pk table='Entertainment' %}" style="text-decoration:none;color:black;"><h5 class="card-title">{{ news.Title }}</h5></a>
                        <p class="card-text"><small class="text-muted">{{ news.publish_time }}</small></p>
                        <p class="card-text">{{ news.Content|range_filter }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <hr>
    <h4><b>খেলাধুলা</b></h4>
    <div class="row">
        <hr>
        {% for news in sports_news %}
            <div class="col-sm-4" style=" border-right: 1px solid #6C758E;">
                <div class="card">
                    <img src="/media/{{ news.content_image }}" class="card-img-top img-thumbnail" alt="{{ news.Title }}" style="display: block; width: 100%; height: 200px;">
                    <div class="card-body">
                        <a href="{% url 'newspaper_project:news_details' pk=news.pk table='Sports' %}" style="text-decoration:none;color:black;"><h5 class="card-title">{{ news.Title }}</h5></a>
                        <p class="card-text"><small class="text-muted">{{ news.publish_time }}</small></p>
                        <p class="card-text">{{ news.Content|range_filter }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    

{% endblock body_block %}

templates/newspaper_project/news_all.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block block_title %}
    Bangladesh
{% endblock block_title %}


{% block body_block %}
    <h3 class="text-center"><b>{{headline}}</b></h3>
    <hr>
    {% for newses in page_obj %}
        <div class="card mb-3 mx-auto" style="max-width: 840px;">
            <div class="row g-0 mx-auto">
                <div class="col-md-4">
                    <img src="/media/{{ newses.content_image }}" alt="{{newses.Title}}" class="img-fluid" style="display: block; width: 100%; height: 200px;">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <a href="{% url 'newspaper_project:news_details' pk=newses.pk table=newses|model_name %}" style="text-decoration:none;color:black;"><h5 class="card-title">{{newses.Title}}</h5></a>
                        <p class="card-text"><small class="text-muted">{{ newses.publish_time }}</small></p>
                    </div>
                </div>
            </div>
      </div>
    {% endfor %}

     <!--Pagination-->
     <div class="container p-4">
        <div class="pagination justify-content-center">
            <span class="step-links">
              {% if page_obj.has_previous %}
                  <a href="?page=1">&laquo; first</a>
                  <a href="?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>

              {% if page_obj.has_next %}
                  <a href="?page={{ movies.next_page_number }}">next</a>
                  <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
              {% endif %}
            </span>
            </div>
        </div>
      <!--end of Pagination-->
{% endblock body_block %}

templates/newspaper_project/news_details.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block block_title %}
    Home
{% endblock block_title %}


{% block body_block %}
    <div class="row">
        <div class="col-sm-8 mx-auto">
            <h3>{{ news.Title }}</h3>
            <p class="card-text"><small class="text-muted">{{ news.publish_time }}</small></p>
            <img src="/media/{{ news.content_image }}" alt="" class="img-fluid">
            <hr>
            <p>{{ news.Content|linebreaks }}</p>
        </div>
    </div>
    <hr>
    <h5>এ সম্পর্কিত আরও পড়ুন</h5>
    <hr>

    {% for rel_news in related_news %}
            <div class="card mb-3 mx-auto" style="max-width: 740px;">
                <div class="row g-0 mx-auto">
                    <div class="col-sm-4">
                    <img src="/media/{{ rel_news.content_image }}" alt="{{rel_news.Title}}" class="img-fluid">
                    </div>
                    <div class="col-md-8">
                    <div class="card-body">
                        <a href="{% url 'newspaper_project:news_details' pk=rel_news.pk table=rel_news|model_name %}" style="text-decoration:none;color:black;"><h5 class="card-title">{{rel_news.Title}}</h5></a>
                        <p class="card-text"><small class="text-muted">{{ rel_news.publish_time }}</small></p>
                    </div>
                    </div>
                </div>
            </div>
    {% endfor %}
    
{% endblock body_block %}