admin_section/urls.py
from django.urls import path
from admin_section import views

app_name = 'admin_section'

urlpatterns = [
    path('', views.log_in, name='login'),
    path('news_admin/', views.news_admin, name='news_admin'),
    path('admin_bangladesh/', views.admin_bangladesh, name='admin_bangladesh'),
    path('admin_international/', views.admin_international, name='admin_international'),
    path('admin_entertainment/', views.admin_entertainment, name='admin_entertainment'),
    path('admin_sports/', views.admin_sports, name='admin_sports'),
    path('admin_trade/', views.admin_trade, name='admin_trade'),
    
]

online_newspaper/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newspaper_project.urls')),
    path('my_admin', include('admin_section.urls')),
    # path('account/', include('app_login.urls')),
    # path('user/', include('app_user_activity.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

admin_section/models.py
from django.db import models

# Create your models here.

admin_section/forms.py
from django import forms
import django
from django.contrib.auth.models import User
from django.forms.models import ModelForm
from newspaper_project import models


class Banglades_news(forms.ModelForm):
    
    class Meta:
        model = models.Bangladesh
        fields = '__all__'


class International_news(forms.ModelForm):
    
    class Meta:
        model = models.International
        fields = '__all__'


class Entertainment_news(forms.ModelForm):
    
    class Meta:
        model = models.Entertainment
        fields = '__all__'


class Sports_news(forms.ModelForm):
    
    class Meta:
        model = models.Sports
        fields = '__all__'


class Trade_news(forms.ModelForm):
    
    class Meta:
        model = models.Trade
        fields = '__all__'

admin_section/views.py
from django.shortcuts import render,HttpResponseRedirect
from newspaper_project import models
from admin_section import  forms
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse,reverse_lazy
from django.contrib.auth.forms import AuthenticationForm


# Create your views here.

def log_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user =  authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('admin_section:news_admin'))
    diction = {'form':form}
    return render(request,'admin_section/login.html',context=diction)

@login_required
def news_admin(request):
    diction = {}

    return render(request,'admin_section/admin_page.html',context=diction)


@login_required
def admin_bangladesh(request):
    form = forms.Banglades_news()
    if request.method == 'POST':
        form = forms.Banglades_news(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_section:news_admin'))
    diction = {'form':form}

    return render(request,'admin_section/admin_bangladesh.html',context=diction)


@login_required
def admin_international(request):
    form = forms.International_news()
    if request.method == 'POST':
        form = forms.International_news(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_section:news_admin'))
    diction = {'form':form}

    return render(request,'admin_section/admin_international.html',context=diction)


@login_required
def admin_entertainment(request):
    form = forms.Entertainment_news()
    if request.method == 'POST':
        form = forms.Entertainment_news(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_section:news_admin'))
    diction = {'form':form}

    return render(request,'admin_section/admin_ent.html',context=diction)


@login_required
def admin_sports(request):
    form = forms.Sports_news()
    if request.method == 'POST':
        form = forms.Sports_news(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_section:news_admin'))
    diction = {'form':form}

    return render(request,'admin_section/admin_sports.html',context=diction)


@login_required
def admin_trade(request):
    form = forms.Trade_news()
    if request.method == 'POST':
        form = forms.Trade_news(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_section:news_admin'))
    diction = {'form':form}

    return render(request,'admin_section/admin_trade.html',context=diction)

templates/admin_section/admin_bangladesh.html
{% extends 'admin_section/admin_page.html' %}
{% load crispy_forms_tags %}


{% block title_block %}

{% endblock title_block %}


{% block body_block %}
     <div class="col-sm-8 mx-auto p-3 border border-success" style="margin-top:100px">
        <h3 class="text-center">বাংলাদেশ</h3>
        <form method="POST" enctype="multipart/form-data">
            {{ form|crispy }}
            {% csrf_token %}
            <input type="submit" name="submit"  value = "Publish" class="mt-4 form-control btn btn-success">
        </form>
    </div>
   
{% endblock body_block %}

templates/admin_section/admin_base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title> 
        {% block title_block %}
            
        {% endblock title_block %}
    </title>
    
  </head>
  <body>
    
    <div class="container mt-4">
        
        {% block body_block %}
            
        {% endblock body_block %}
            
    </div>




    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
<script>
    baguetteBox.run('.tz-gallery');
</script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/admin_section/admin_ent.html
{% extends 'admin_section/admin_page.html' %}
{% load crispy_forms_tags %}

{% block title_block %}

{% endblock title_block %}


{% block body_block %}
<div class="col-sm-8 mx-auto p-3 border border-success" style="margin-top:100px">
    <h3 class="text-center">বিনোদন</h3>
    <form method="POST" enctype="multipart/form-data">
        {{ form|crispy }}
        {% csrf_token %}
        <input type="submit" name="submit"  value = "Publish" class="mt-4 form-control btn btn-success">
    </form>
</div>
{% endblock body_block %}

templates/admin_section/admin_international.html
{% extends 'admin_section/admin_page.html' %}
{% load crispy_forms_tags %}

{% block title_block %}

{% endblock title_block %}


{% block body_block %}
<div class="col-sm-8 mx-auto p-3 border border-success" style="margin-top:100px">
    <h3 class="text-center">আন্তর্জাতিক</h3>
    <form method="POST" enctype="multipart/form-data">
        {{ form|crispy }}
        {% csrf_token %}
        <input type="submit" name="submit"  value = "Publish" class="mt-4 form-control btn btn-success">
    </form>
</div>
{% endblock body_block %}

templates/admin_section/admin_page.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title> 
        {% block title_block %}
            
        {% endblock title_block %}
    </title>
    
  </head>
  <body>
    <div class="row text-center" style="background: #EAEEEF">
      <div class="col-sm-12"><p class="navbar-brand" style="font-size: 40px;font-weight: 800;">স্বদেশ বার্তা</p></div>
    </div>
    <hr class="m-0 p-0" style="height: 0.5px;">
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 mx-auto">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'admin_section:admin_bangladesh' %}">বাংলাদেশ</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin_section:admin_international' %}" style="color: black;">আন্তর্জাতিক</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin_section:admin_trade' %}" style="color: black;">বাণিজ্য</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin_section:admin_entertainment' %}" style="color: black;">বিনোদন</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin_section:admin_sports' %}" style="color: black;">খেলাধুলা</a>
            </li>
          </ul>
          
        </div>
      </div>
    </nav>
    <hr class="m-0 p-0" style="height: 1.2px;">
      
    
    <div class="container mt-4">
        
        {% block body_block %}
            
        {% endblock body_block %}
            
    </div>




    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
<script>
    baguetteBox.run('.tz-gallery');
</script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/admin_section/admin_sports.html
{% extends 'admin_section/admin_page.html' %}
{% load crispy_forms_tags %}

{% block title_block %}

{% endblock title_block %}


{% block body_block %}
<div class="col-sm-8 mx-auto p-3 border border-success" style="margin-top:100px">
    <h3 class="text-center">খেলাধুলা</h3>
    <form method="POST" enctype="multipart/form-data">
        {{ form|crispy }}
        {% csrf_token %}
        <input type="submit" name="submit"  value = "Publish" class="mt-4 form-control btn btn-success">
    </form>
</div>
{% endblock body_block %}

templates/admin_section/admin_trade.html
{% extends 'admin_section/admin_page.html' %}
{% load crispy_forms_tags %}

{% block title_block %}

{% endblock title_block %}


{% block body_block %}
<div class="col-sm-8 mx-auto p-3 border border-success" style="margin-top:100px">
    <h3 class="text-center">বাণিজ্য</h3>
    <form method="POST" enctype="multipart/form-data">
        {{ form|crispy }}
        {% csrf_token %}
        <input type="submit" name="submit"  value = "Publish" class="mt-4 form-control btn btn-success">
    </form>
</div>
{% endblock body_block %}

templates/admin_section/login.html
{% extends 'admin_section/admin_base.html' %}
{% load crispy_forms_tags %}

{% block title_block %}
    Log In
{% endblock title_block %}

{% block body_block %}
    <div class="col-sm-8 mx-auto p-3 border border-success" style="margin-top:100px">
        <h3 class="text-center">Log in to connect with Everyone</h3>
        <form method="POST">
            {{ form|crispy }}
            {% csrf_token %}
            <input type="submit" name="submit"  value = "Log In" class="mt-4 form-control btn btn-success">
        </form>
    </div>
   
{% endblock body_block %}