admin_section/urls.py
from django.urls import path
from admin_section import views

app_name = 'admin_section'

urlpatterns = [
    path('', views.log_in, name='login'),
    path('news_admin/', views.news_admin, name='news_admin'),
    path('admin_bangladesh/', views.admin_bangladesh, name='admin_bangladesh'),
    path('admin_international/', views.admin_international, name='admin_international'),
    path('admin_entertainment/', views.admin_entertainment, name='admin_entertainment'),
    path('admin_sports/', views.admin_sports, name='admin_sports'),
    path('admin_trade/', views.admin_trade, name='admin_trade'),
    
]

newspaper_project/urls.py
from django.urls import path
from newspaper_project import views

app_name = 'newspaper_project'

urlpatterns = [
    path('', views.home, name='home'),
    path('news_details/<pk>/<table>', views.news_details, name='news_details'),
    path('news_Bangladesh/', views.news_Bangladesh, name='news_Bangladesh'),
    path('news_International/', views.news_International, name='news_International'),
    path('news_Trade/', views.news_Trade, name='news_Trade'),
    path('news_Entertainment/', views.news_Entertainment, name='news_Entertainment'),
    path('news_Sports/', views.news_Sports, name='news_Sports'),
    
]

online_newspaper/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newspaper_project.urls')),
    path('my_admin', include('admin_section.urls')),
    # path('account/', include('app_login.urls')),
    # path('user/', include('app_user_activity.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title> 
        {% block title_block %}
            
        {% endblock title_block %}
    </title>
    
  </head>
  <body>
    <div class="row">
      <div class="col-sm-4 text-center" style="padding: 0px; background: #053C29;">

      </div>

      <div class="col-sm-3 text-center" style="background: rgb(248, 4, 4);">
        <p style="font-size: 40px;font-weight: 800; padding: 0px;"><a href="{% url 'newspaper_project:home' %}" style="text-decoration: none; color: white;">স্বদেশ বার্তা</a></p>
      </div>

      <div class="col-sm-5 d-flex flex-row-reverse" style="background: #053C29;">
          <img src="/media/flag.gif" alt="" class="image-fluid" style="height:75px;">
      </div>
      
    </div>
    <hr class="m-0 p-0" style="height: 0.5px;">
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top" style="padding-bottom: 2px;">
      <div class="container-fluid">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 mx-auto">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'newspaper_project:news_Bangladesh' %}" style="font-weight: 700; margin-left: 25px;">বাংলাদেশ</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'newspaper_project:news_International' %}" style="color: black; font-weight: 700; margin-left: 25px;">আন্তর্জাতিক</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'newspaper_project:news_Trade' %}" style="color: black; font-weight: 700; margin-left: 25px;">বাণিজ্য</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'newspaper_project:news_Entertainment' %}" style="color: black; font-weight: 700; margin-left: 25px;" >বিনোদন</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'newspaper_project:news_Sports' %}" style="color: black; font-weight: 700; margin-left: 25px;">খেলাধুলা</a>
            </li>
          </ul>
          <form class="d-flex" method="GET">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
          </form>
        </div>
      </div>
    </nav>
    <hr class="m-0 p-0" style="height: 1.2px;">
      
    
    <div class="container mt-4">
        
        {% block body_block %}
            
        {% endblock body_block %}
            
    </div>

     <!-- footer section -->
    <hr style="height: 0.2px; margin-top: 100px;">
      <div class="row m-4">
        <div class="col-sm-12">
          <p style="font-size: 20px;font-weight: 800;"><a href="{% url 'newspaper_project:home' %}" style="text-decoration: none; color: black;">স্বদেশ বার্তা</a></p>
        </div>
      </div>

      <div class="row m-4 text-center" style="font-size: 14px;">
        <div class="col-sm-2 mx-auto" style=" border-right: 1px solid #6C758E;">
          <p><a href="{% url 'newspaper_project:news_Bangladesh' %}" style="text-decoration: none; color: black;">বাংলাদেশ</a></p>
          <p><a href="{% url 'newspaper_project:news_International' %}" style="text-decoration: none; color: black;">আন্তর্জাতিক</a></p>
          <p><a href="{% url 'newspaper_project:news_Trade' %}" style="text-decoration: none; color: black;">বাণিজ্য</a></p>
        </div>
        <div class="col-sm-3 mx-auto" style=" border-right: 1px solid #6C758E;">
          <p><a href="{% url 'newspaper_project:news_Entertainment' %}" style="text-decoration: none; color: black;">বিনোদন</a></p>
          <p><a href="{% url 'newspaper_project:news_Sports' %}" style="text-decoration: none; color: black;">খেলাধুলা</a></p>
          <p><a href="" style="text-decoration: none; color: black;">বিজ্ঞান</a></p>
        </div>

        <div class="col-sm-3 mx-auto" style=" border-right: 1px solid #6C758E;">
          <p><a href="" style="text-decoration: none; color: black;">বিশেষ সংখ্যা</a></p>
          <p><a href="" style="text-decoration: none; color: black;">গোলটেবিল</a></p>
          <p><a href="" style="text-decoration: none; color: black;">অন্য বার্তা</a></p>
        </div>

        <div class="col-sm-2 mx-auto">
          <p><a href="" style="text-decoration: none; color: black;">বিজ্ঞাপন</a></p>
          <p><a href="" style="text-decoration: none; color: black;">যোগাযোগ</a></p>
        </div>
      </div>

      <div class="row text-center" style="background: #c0c8df;">
        <div class="col-sm-12 p-2">
          <a href="" style="margin-right: 8px; border-radius: 50%; display: inline-block; height: 30px;width: 30px;background-color: white; font-size: 20px;text-align: center;color: teal;"><i class="fa fa-facebook" aria-hidden="true"></i></a>
          <a href="" style="margin-right: 8px; border-radius: 50%; display: inline-block; height: 30px;width: 30px;background-color: white; font-size: 20px;text-align: center;color: teal;"><i class="fa fa-twitter" aria-hidden="true"></i></a>
          <a href="" style="border-radius: 50%; display: inline-block; height: 30px;width: 30px;background-color: white; font-size: 20px;text-align: center;color: teal;"><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
        </div>
      </div>
      <div class="row m-auto text-center" style="padding-top: 5px; margin: 0px; ">
        <p style="padding-top: 8px; padding-bottom: 0px; font-size: 12px; color: #9FA6C4;"> স্বত্ব &copy; ২০২১ স্বদেশ বার্তা | সম্পাদক ও প্রকাশক: মো: হানিফ উল্লাহ</p>
      </div>
    




    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
<script>
    baguetteBox.run('.tz-gallery');
</script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>